[Circuit_Version]
RLN_Version = 2
RLN_Type = "rln"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.5"
GitHub_URL = "https://github.com/Rate-Limiting-Nullifier/rln-circuits-v2.git"
Git_Commit = "17f0fed"
Compilation_Time = 1688818882

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "fa9586db68a9566fd9b3af6e8d7c66f5567b35647aa63a426f220375e9fa8c04"
Zkey = "final.zkey"
Zkey_SHA256SUM = "5eaad7aae4dcc269e7de5b4e1aad7578cc3316ce1e2923c72c0eacf8d8a7c3c1"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "6a45165b480239cac8e2de450f488e37198a18297db55a9509589c14b7db59f7"
