[Circuit_Version]
RLN_Version = 2
RLN_Type = "withdraw"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.5"
GitHub_URL = "https://github.com/Rate-Limiting-Nullifier/rln-circuits-v2.git"
Git_Commit = "17f0fed"
Compilation_Time = 1688818887

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "239bd578deea5eebf3cde5a9aeba22ba799d23d0aff6b9a8b153afd8d2cc191e"
Zkey = "final.zkey"
Zkey_SHA256SUM = "397b769ddcf0bd918e5a85566e978150917da38020ab8e9ce878a6492bf2bca8"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "a00c881245625369f18593dcd796188f457bd9cb38c6772e662febf2faec6160"
